### ISSUE TITLE
Missing blocks

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#117]
@Adi-UA  - I'm getting the following error message on trying to run a mission - I think it's related to the removal of the BlockAsistButton and BlockAsistLever classes in #114 .

<img width="966" alt="image" src="https://user-images.githubusercontent.com/653549/79902028-a0ee7700-83c5-11ea-8788-4b184c51e167.png">

When I click 'Yes' and go into the compound, I see that the blocks do not have buttons:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/653549/79902065-aea3fc80-83c5-11ea-9903-a9c0261615d3.png">

Do you need to update the worlds on vanga?

**Comment by Adi-UA** [comment]
Ah yes
Sorry, I need to push the new worlds to Vanga

**Comment by adarshp** [comment]
> Ah yes Sorry, I need to push the new worlds to Vanga
> […](#)

Got it - let us know when you've uploaded them - thanks!

**Comment by Adi-UA** [comment]
The worlds have been updated.

**Comment by adarshp** [comment]
Thanks!
