### ISSUE TITLE
Integrate multiplayer voice chat

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#165]
A significant part of the ToMCAT research effort involves analyzing spoken human dialogue between members of a team that are trying to accomplish a mission. This will become particularly salient as we go into phase 2 (approximately February 2021). 

For this reason, we would like to incorporate multiplayer voice chat in our framework.

I found at least one open-source client that we could use: https://www.mumble.info. Perhaps there are others - we should do a bit of a survey.

The reason we're not using something like Zoom is to enable greater automation of the experiment via scripting, and have more control over when the recording starts, and thus align the audio recording with the duration of the mission.

Integrating an open-source voice chat client will likely not involve writing any C or C++ code, but will likely involve writing a few bash scripts to glue things together.

@meghavarshini I'm tagging you in the issue since you'll be working on this over the summer.

**Comment by BeckySharp** [comment]
- [ ] survey, decide which tool to use (community of users)
- [ ] read through docs / tutorials
- [ ] get toy running, min working example
- [ ] integrate with run_session

**Comment by adarshp** [comment]
After a good deal of experimentation, we have decided to jettison Mumble+headsets in favor of non-noise canceling headphones so that the participants can hear each other (since they are in the same room) and standalone directional microphones that can focus on a single participant's voice.

See #278 for more details.
