### ISSUE TITLE
Make port_forwarder script more organized

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#206]
The `port_forwarder` script should check whether a port has already been forwarded before trying to forward it. @jastier could you please 'robustify' the script in this way? 

https://github.com/ml4ai/tomcat/blob/multiplayer/tools/port_forwarder

**Comment by jastier** [comment]
Added a single port forwarder script, and a multi line batch processing script that can call it n times.
"start", "stop", and "status" of ports forwarded to host machines are supported.
Merged onto ml4ai/tomcat/tools on November 6.    
Done.

**Comment by adarshp** [comment]
Closed by #208.
