### ISSUE TITLE
Eyetracking data stream from Lion is not detected by LabRecorder

### ISSUE THREAD

**Issue by val-pf** [ml4ai/tomcat#237]
At Friday's pilot (02/25) we had to restart pupil capture a few times before it was operational, and we were unable to steam data from Lion, despite it recording.
Troubleshooting we tried: 

- restarting Pupil Capture
- restarting lion
- force quit pupil capture
- swapping the physical eyetracker with a spare

Would recommend removing and re-installing software (pupil capture) as a first step

**Comment by chinmaib** [comment]
For missing eye-tracker stream from Lion, It might help to check by opening the "Pupil Capture" application, going to "settings" or "plugins", and check if the "LSL relay" option is turned on.

**Comment by chinmaib** [comment]
I believe the software install file is already located in the Downloads folder. 
Here is the link to download again if necessary: https://docs.pupil-labs.com/core/

**Comment by val-pf** [comment]
I reinstalled the software and activated the LSL relay setting. We should test this, but it may very well be solved.

**Comment by eduongAZ** [comment]
Testing session today indicates that this issue is solved.
