### ISSUE TITLE
ffmpeg currently captures input from eye tracker rather than the iMac webcam

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#240]

**Comment by CalebUAz** [comment]
ffmpeg -f avfoundation -framerate 30 -i "FaceTime HD Camera" -vf fps=5 _<File_path>_

@eduongAZ  I tried this out and this supposedly should fix the issue.

**Comment by CalebUAz** [comment]
@eduongAZ  run this just to confirm the name of the webcam that the iMac uses: `ffmpeg -f avfoundation -list_devices true -i "" `

**Comment by eduongAZ** [comment]
As suggested by @CalebUAz, using device name works.
