### ISSUE TITLE
The clock on the windows machine is behind by an hour which is causing timing issues with LSL.

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#241]

**Comment by eduongAZ** [comment]
Would updating the Window machines' clock to match the time of iMacs, ToM, and CAT solve this issue?

Also @CalebUAz this could perhaps prevent you from pairing LSL timestamp with baseline tasks.

**Comment by CalebUAz** [comment]
@eduongAZ I'm not sure whether it will solve the issue or not. 

Can we switch from time.time() to time.monotonic() and do a dry run just to see if I can sync the baseline task with the Physio data?

**Comment by CalebUAz** [comment]
As a temporary solution, I used my phone as the modem and updated the clock on the windows machine by syncing it with the windows server.

**Comment by eduongAZ** [comment]
@CalebUAz provided the [document](https://docs.google.com/document/d/17iDVugiepXJbUjFuFjx_7Ra3zQfbwS8rCXX_kFfhvDY/edit) detailing how we were able to provide Internet access to the Windows computer

**Comment by eduongAZ** [comment]
Since #261 is solved, perhaps this issue can now be solved as well?

**Comment by adarshp** [comment]
This is now resolved.
