### ISSUE TITLE
Sending a small file to ToM's NFS mounted drive from iMacs takes about 7 seconds for the file to show up on ToM's NFS mounted drive

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#243]

**Comment by kobus-barnard** [comment]
This might go away with other changes. But we need to be able to measure IO performance.

**Comment by eduongAZ** [comment]
Sending a file from CAT to ToM's NFS drive and sending a file from ToM to CAT's NFS drive are instantaneous. 

However, sending file from lion iMac to CAT's NFS drive fails with error: `copy extended attribute: operation not permitted`, and sending a file from tiger iMac to CAT's NFS drive succeeds without any error, but took 5 seconds.

Sending file from tiger iMac to ToM's NFS drive succeeds after 5 seconds with error: `copy extended attribute: operation not permitted`, and sending a file from lion iMac to ToM's NFS drive succeeds without any error, but took 5 seconds.

**Comment by kobus-barnard** [comment]
Searching with Google on slow mac nfs brings up a lot of hits, even some with Catalina. Have you look at some of these? 

If this cannot work, we can consider alternatives. But I prefer getting it to work.

**Comment by eduongAZ** [comment]
Problem fixed using #256 solution.
