### ISSUE TITLE
Document that lists things to check and instructions for repairing them

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#250]
We need a document that lists things to check (and instructions for repairing them), such as LSL on the macs. We need to check all this with enough advance time to fix them for each experiment. Eventually, this can largely be assigned to undergraduates, but a grad student needs to be around anyway.

**Comment by eduongAZ** [comment]
Document can be accessed [here](https://docs.google.com/document/d/1rW3I87epouyI6bgkf71FirPpIENsDBSIBgDt8zh_Jpc/edit?usp=sharing)
