### ISSUE TITLE
Stream noisy data of EEG, fNIRS, and eyetracker for testing purposes

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#251]
We need a way to stream noisy data of EEG, fNIRS, and eyetracker to test the recording process. @val-pf @chinmaib do you have any suggestions on how we can do so?

**Comment by adarshp** [comment]
The ffmpeg issue (#260) needs to be resolved first before we can make progress on this issue.

**Comment by adarshp** [comment]
@chinmaib  - if the instructions are detailed, consider making a Google doc and putting it [here](https://drive.google.com/drive/u/0/folders/17o8YdVL8xofatSeUvmVRbHHBfmThgh3c)

**Comment by val-pf** [comment]
https://github.com/val-pf/tomcat-equipment-wiki/wiki here is the link to the undergrad Physio-Wiki that has it all. 
I will add a section for how to steam just noisy data at glance. In essence, you just leave out putting anything on a cap, person, or applying any gel to the components.

**Comment by val-pf** [comment]
https://github.com/val-pf/tomcat-equipment-wiki/wiki/Dry-run-(streaming-noisy-data)

**Comment by adarshp** [comment]
@val-pf Thanks for setting up the wiki! I've [added a link to it on the ToMCAT webpage](https://github.com/ml4ai/tomcat/commit/4de61eea94bb778536a626ba0cbc8eeeaa9f62b0#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c4680dfa534R83)
