### ISSUE TITLE
LabRecorder running on CAT computer cannot detect LSL streams from Windows and iMac machines

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#252]
LabRecorder is installed on ToM and CAT computers, but it cannot detect data streaming from Windows and iMac computers.

**Comment by adarshp** [comment]
@chinmaib says there is some network troubleshooting that needs to be done. Will SSH into the machine and try to figure out what's going on.

**Comment by adarshp** [comment]
@chinmaib needs to be in the lab to run some GUI programs. Will take care of it in the next few days.

**Comment by chinmaib** [comment]
Network LSL issues resolved. LSL streams from the iMacs and the windows machine are now detected on LabRecorder application running on CAT server. The details of LabRecorder installation, configuration, and running is specified in the google  document linked below:
[https://docs.google.com/document/d/1y-AVGpYc8beLalI7o_S3kjw0Xj9lBUsuNdKNXxuWjAA/edit?usp=sharing]
