### ISSUE TITLE
Test NFS latency of ToM and CAT

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#255]
It would be useful to test NFS performance of ToM and CAT to ensure that the network is capable of transmitting and storing data.

- [x] Test sending data from each iMac to ToM and CAT via `dd if=/dev/zero of=/Users/LabWorker/data/cat bs=4096 count=100000` and `dd if=/dev/zero of=/Users/LabWorker/data/tom bs=4096 count=100000`.
- [x] Test sending screen and webcam images from `ffmpeg` to ToM and CAT.
- [x] Test sending data while streaming EEG, fNIRS, eyetracking, baseline tasks, and Minecraft data through the network.

**Comment by adarshp** [comment]
Things work smoothly after switching the version of NFS on iMacs from 4 to 3. Item 3 will be done on 3/17 at the testing session.

**Comment by adarshp** [comment]
This issue is also blocked by #260 .

**Comment by eduongAZ** [comment]
When connecting to testbed, streaming EEG, fNIRS, and eye-tracking, sending 4Mb image from an iMac to CAT takes on average 0.3 milliseconds.
