### ISSUE TITLE
Create a document describing the lab computer and sensor architecture, including a 'wiring diagram' describing what is connected to what

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#257]

**Comment by adarshp** [comment]
@rchamplin - for now, you can make this document a Google doc in [this folder](https://drive.google.com/drive/u/0/folders/17o8YdVL8xofatSeUvmVRbHHBfmThgh3c). Later, we might move it to another location.

**Comment by adarshp** [comment]
In progress. @rchamplin is waiting on request for Microsoft Visio to create the wiring diagram.

**Comment by eduongAZ** [comment]
[ToMCAT Lab - Network & Wiring Diagram.pdf](https://github.com/ml4ai/tomcat/files/8476781/ToMCAT.Lab.-.Network.Wiring.Diagram.pdf)

Created by @rchamplin
