### ISSUE TITLE
Server issue with rest state part of the baseline task

### ISSUE THREAD

**Issue by CalebUAz** [ml4ai/tomcat#258]
The `rest_state_client`  [[1]](https://github.com/ml4ai/tomcat-baseline-tasks/blob/rest_state/tasks/rest_state/client_rest_state.py) never receives the countdown timer data from the `rest_state_server` [[2].](https://github.com/ml4ai/tomcat-baseline-tasks/blob/rest_state/tasks/rest_state/server_rest_state.py) 
Will resolve the issue with @eduongAZ!

**Comment by eduongAZ** [comment]
Moving this issue over to https://github.com/ml4ai/tomcat-baseline-tasks/issues/42 to track it in the baseline task repository.
