### ISSUE TITLE
Reduce ffmpeg image resolution

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#260]

**Comment by adarshp** [comment]
We will go with trying to reduce the resolution rather than reducing the framerate, since we can get more accurate data with 20Hz framerate, easier to align with other streams.

**Comment by eduongAZ** [comment]
Reducing resolution of webcam and screen images reduces the CPU load. Streaming screen takes the most amount of CPU time.

Streaming webcam at resolution 1280x720 and screen at resolution 1280x720 takes 35% CPU.
Streaming webcam at resolution 1280x720 and screen at resolution 2560x1440 takes 65% CPU.

I will stream both at 1280x720 resolution, which seems to work well with no issue.

**Comment by adarshp** [comment]
Thanks @eduongAZ - this seems like a good solution.
