### ISSUE TITLE
Provide Internet access to Windows machine

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#261]
@CalebUAz provided the [document](https://docs.google.com/document/d/17iDVugiepXJbUjFuFjx_7Ra3zQfbwS8rCXX_kFfhvDY/edit) detailing how we were able to provide Internet access to the Windows computer

**Comment by adarshp** [comment]
Update - the new location of the document is [here](https://docs.google.com/document/d/1jnXt-JtwNi_QG4cIhl7dSSalSF9GbgXr/edit?rtpof=true)
