### ISSUE TITLE
Triggers for brain recording

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#262]
@val-pf suggested having 'triggers' for brain recording. These triggers are already present in the form of messages on the message bus for the Minecraft task, and can be implemented for the baseline tasks as well (see https://github.com/ml4ai/tomcat-baseline-tasks/issues/45). @chinmaib will discuss testbed architecture with @val-pf .

**Comment by eduongAZ** [comment]
It seems that we don't need triggers for brain recording because the baseline tasks and Minecraft already include timestamps that we can use to pair with physio recordings.
