### ISSUE TITLE
LSL streams visualization

### ISSUE THREAD

**Issue by chinmaib** [ml4ai/tomcat#268]

**Comment by adarshp** [comment]
@chinmaib  - I recently got a seed grant to fund 50% of @vincentraymond-ua 's time this semester to create an open-source dashboard for conducting ToMCAT (and related) experiments, including visualizing sensor streams on the dashboard. I had in mind some of this stuff (visualizing LSL streams) when I wrote that proposal. Let's discuss on Monday whether the dashboard work can contribute to this issue (I think it potentially can).

**Comment by eduongAZ** [comment]
We are using `lsl_viewer` software as a temporary solution. We might need a different solution that is long-term.
