### ISSUE TITLE
Eye-tracker (pupil labs) recordings need to be saved on CAT through NFS

### ISSUE THREAD

**Issue by chinmaib** [ml4ai/tomcat#269]

**Comment by chinmaib** [comment]
The record option on Pupil Core software records the pupil video, world camera video, coordinates, and several other valuable eye-tracker related data locally onto the iMacs they are running on. The average size of one session data is approximately 40 GB. The iMac memory of 512 GB will be quickly depleted. I believe this data is not required to be processed in real-time, but it contains valuable information.
We need to come up with a post-experiment script to move these files to NFS location or have the Pupil Core software write directly to the NFS location. This is dependent on how much traffic the network can handle.

**Comment by CalebUAz** [comment]
I did this on lion iMac and it saves all pupil capture data on CAT! However, I need @chinmaib @eduongAZ to check if the path where it's saving is appropriate/correct!

**Comment by eduongAZ** [comment]
Discussion with Chinmai concluded that we will save eye tracker video locally on the iMacs to conserve network card usage on the iMacs.
