### ISSUE TITLE
Remove echos when talking through Mumble

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#276]
The participants complained that the echos in Mumble cause headache. The mic of one participant picks up the voice of another participant.

**Comment by adarshp** [comment]
There is a setting in Mumble that we can tweak to suppress the echoes.

**Comment by vincentraymond-ua** [comment]
Somewhere on the Client machines, there is a file named mumble_audio_wizard.zip. It used to be on the Desktop, but it may have been moved. This zip file contains step-by-step instructions on how to properly calibrate audio using the Mumble Audio Wizard. This would likely help some of the audio issues we are experiencing.

**Comment by adarshp** [comment]
TODO @vincentraymond-ua  - integrate the contents of `mumble_audio_wizard.zip` into the tomcat-equipment-wiki wiki: https://github.com/ml4ai/tomcat-equipment-wiki/wiki

**Comment by vincentraymond-ua** [comment]
The contents of mumble_audio_wizard.zip have now been integrated into the tomcat-equitment-wiki. However, it is uncertain if they will stay there long term. This issue is linked to #288

**Comment by adarshp** [comment]
Thank you @vincentraymond-ua !

**Comment by adarshp** [comment]
Update: This will be tested tomorrow.

**Comment by eduongAZ** [comment]
We can tune Mumble to remove echo by using Configure -> Audio Wizard. However, this tuning process has to be configured for each participant. This tuning process will be part of the experiment procedure.
