### ISSUE TITLE
Eye tracker issues

### ISSUE THREAD

**Issue by CalebUAz** [ml4ai/tomcat#283]
![image](https://user-images.githubusercontent.com/90938130/162549445-8b4c8f90-7414-4489-8eb3-fac716e4a67f.png)
***Pupil capture shows confidence scores for each eye***

Every time you blink the confidence drops to ~0.5. 

When LSL streams eye tracker data it combines confidence for both eyes:
![image](https://user-images.githubusercontent.com/90938130/162549640-f7f166cb-20ee-471d-87e7-a983f32123b7.png)
***10.7% of the entire eye tracking data had less than 0.5 confidence values.***

Also I was scrubbing through the world view video timeline for pilot session on March 1st on one of the iMacs and I noticed that top of the screen gets chopped off when the subjects were playing Minecraft: 
![image](https://user-images.githubusercontent.com/90938130/162549868-7896bba5-eb03-41d1-a5ee-31941b0cc99c.png)
Not sure if this reduces the confidence interval or not!

**Comment by eduongAZ** [comment]
I don't think there is anything we can do to handle the confidence interval decrease caused by eye-blinking, since it is computed by the eye-tracking software. 

We should still capture the confidence interval in our data for analysis.
