### ISSUE TITLE
Develop uber-script

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#287]
Update: The uber-script is becoming more urgent.

Kobus: We should have a draft of this script by next week (April 18, 2022).

Related to #286 , #248

**Comment by adarshp** [comment]
We should also update the instructions to describe how to run the uber-script. It should be readable by both CS and social science people.

**Comment by adarshp** [comment]
Requirement: There should be a 'debug' mode for the uber-script.

**Comment by adarshp** [comment]
Requirement: 

We should eliminate the manual launching of the ffmpeg processes for capturing face and screen video.

Kobus: We should add the launching of the AppleScript that is being currently manually launched to the uber-script.

**Comment by paulosoaresua** [comment]
I started a draft for the uber script. I am working on the branch `uber_script`. I am placing the scripts in `tools/lab_scripts`. So far I have a pre_baseline script that does the following:

1. Launches Minecraft
2. Grabs the player name from the log messages
3. Opens the client map and populates the player name field with the value found
4. Changes the size and location of the browser and Minecraft

OBS: I had to use change from Firefox to Safari as there is no support to execute a javascript on Firefox from an applescript. On Safari, the client map launched correctly and the audio and survey buttons seemed to work well, so this change might not be a problem.

**Comment by adarshp** [comment]
Update: This will be tested tomorrow.

**Comment by paulosoaresua** [comment]
I refactored most of the original UberScript I wrote. The script is better organized and dependent scripts can be executed independently if necessary. Some steps like launching Minecraft, opening the client map, the final survey, and cleaning things up will be addressed in future branches.

**Comment by adarshp** [comment]
Closed by #318
