### ISSUE TITLE
ToMCAT agent intervention does not show up on Minecraft clients

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#290]
When launching the agent using docker-compose for the first time, then the agent interventions didn't show on the Minecraft clients. Then, stopping the docker-compose agent and launching the agent on dashboard, the intervention showed up on Minecraft clients.

However, in the past, we were able to get the interventions to show up even when agent was manually launched using docker-compose.

The reason that we need the launch the agent manually is to get the log file of the agent.

**Comment by vincentraymond-ua** [comment]
This is a complex issue. There is a filter that prevents unauthorized agents from producing intervention messages. However, there is a way around this that I think we accidentally discovered. If you try to launch the agent from the dashboard first, and then shut it down, you can launch the agent manually using docker-compose and have its messages shown in Minecraft. 

Essentially, launching it through the dashboard first will authorize the agent/intervention/ASI_UAZ_TA1_ToMCAT/chat messages.

**Comment by eduongAZ** [comment]
Will follow steps outlined by Vincent until testbed outputs agent log file.

**Comment by eduongAZ** [comment]
The testing session shows that the steps outlined by Vincent works.
