### ISSUE TITLE
Improve baseline tasks program performance while running Minecraft and ClientMap in the background

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#291]
Running `renice -3` on baseline tasks program process allows ping-pong to be playable when running Minecraft and ClientMap in the background, but framerate is poor. However, it crashed the ping-pong client on Cheetah.

Maybe `renice -5` might solve the issue.

**Comment by CalebUAz** [comment]
A rough draft of the apple script that executes baseline task with a predefined priority has been implemented on leopard.

**Comment by eduongAZ** [comment]
With UberScript handling software set up, this issue is no longer relevant.
