### ISSUE TITLE
Aurora stops working after quit & prevents shutdown 

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#297]
At the stress test on 04/19, we noticed that after data collection was finished, Aurora refused to shut down properly on Leopard and Lion.
Solution: go to activity monitor, double click on aurora, select "force quit".
This worked for Leopard, but not for Lion, although it initially looked as if it had worked for both.

We tried to shut down Lion, and it seemed to work, but some reminiscent piece of the bugging aurora software prevented the shutdown at the last instance (without throwing an error). Solution: Click on the apple symbol (top left), choose "force quit" and select Aurora. Only then, the shutdown will complete.
We need to monitor these issues to make sure we can safely shutdown all iMacs.

**Comment by adarshp** [comment]
We have a solution for this, @chinmaib will close when it is implemented.

**Comment by CalebUAz** [comment]
Issue was due to writing NIRS files over NFS. Now since we restored the write location to local machine, the issue has been resolved.
