### ISSUE TITLE
ToMCAT dialog agent does not start with testbed_up_core -a -w options

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#303]
When launching the testbed with `./testbed_up_core.sh -a -w`, the log shows "Skipping UAZ Dialog agent."

**Comment by adarshp** [comment]
@eduongAZ you'll need to add the `-d` flag as well.

**Comment by adarshp** [comment]
Decision: We will use the `-i` flag instead, as in:

```
./testbed_up_core.sh -i
```

This will bring up all the ACs.
