### ISSUE TITLE
Remmina and Mumble cannot launch on ToM

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#304]
After clicking on Remmina and Mumble launcher, the application windows did not show up.

**Comment by CalebUAz** [comment]
I believe the reboot fixed the issue.

**Comment by kobus-barnard** [comment]
Close when documented that this needs to be checked at start up.

**Comment by eduongAZ** [comment]
Related to #281

**Comment by eduongAZ** [comment]
Fixed after rebooting.
