### ISSUE TITLE
Testbed installation on Tom potentially missing recent agent updates 

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/tomcat#309]
Since our last Testbed update,  I believe there have been a number of updates to agents that been published that would be beneficial to include in our own Testbed installation.

- An update to the DialogAgent to fix a bug where messages were not being published after the Training missing
-  An update to the SpeechAnalyzer to drastically reduce CPU usage
- An update to the ASR_Agent that changes the way audio chunks are sent to the speechAnalyzer

Also, if we are not already, we may want to document the current version of the Testbed in use and when it was last updated.

**Comment by adarshp** [comment]
Perhaps we should have a `langlab` branch that we run the Lang Lab experiments off of? We can then incorporate whatever changes we want into it regardless of whether the relevant changes have been merged into `develop` or not (the ASR agent binary chunk publishing update has not been merged into `develop` yet).

**Comment by kobus-barnard** [comment]
Perhaps the best solution.

**Comment by eduongAZ** [comment]
I agree with having the `langlab` branch. This will be the branch we use for dry runs and experiments.

**Comment by adarshp** [comment]
Update: @vincentraymond-ua  will do this soon.

**Comment by vincentraymond-ua** [comment]
The `langlab` branch has been created from the version pinned this past Friday for Study3 data collection.

Going forward, all Testbed modifications will be done through this branch.
