### ISSUE TITLE
Cannot select experiment in testbed

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#313]
![image](https://user-images.githubusercontent.com/86935179/166391266-51eb7666-6e7a-4126-94d4-3562bb8076f3.png)
Even after creating new experiment, shut down testbed and start it again (option -i), I cannot select experiment to start Minecraft mission.

**Comment by vincentraymond-ua** [comment]
Check the browser console by pressing 'f12', are there any errors that are shown when trying to select an experiment?

**Comment by eduongAZ** [comment]
Issue is not encountered during the dry run today
