### ISSUE TITLE
Extract Minecraft mission data

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#316]
Only header data was extracted from the metadata of the dry run Minecraft mission. The extraction was done on Chrome.

**Comment by vincentraymond-ua** [comment]
When exporting a replay, there are two options that you must specify:

1. Trial UUID
2. Index

You have to use the Index associated with the Trial for the .metadata to export correctly. Otherwise, you will see the behavior where only the header data is exported.

**Comment by chinmaib** [comment]
Vincent, that you for the comment. Yes, currently I am able to extract only the header. Could you let me know how to find the index for the trial?
There is an index specified in the extracted header. Can we use that?

**Comment by chinmaib** [comment]
Here is an example of the header information I extracted.
{
"header":{"timestamp":"2022-05-03T18:34:46.332Z","message_type":"export","version":"filebeat-7.2.0-2022.05.03"},
"msg":{
	"sub_type":"trial",
	"source":"metadata-web",
	"experiment_id":"d375096c-4d39-44a8-8ba6-72abb63dd2f9",
	"trial_id":"a8311b3b-cd3c-462b-90a6-5648ad26777f",
	"timestamp":"2022-05-03T18:34:46.332Z",
	"version":"3.5.3-dev-88-g5bf199f9"},
"data":{
	"index":"filebeat-7.2.0-2022.05.03",
	"metadata":{"trial":{"name":"Dry run 5-3-22",
	"date":"2022-05-03T18:10:30.134200Z",
	"experimenter":"Eric Duong",
	"subjects":["P00010","P00011","P00012"],
	"trial_number":"1",
	"group_number":"1",
	"study_number":"1",
	"condition":"NA",
	"notes":["NA"],
	"testbed_version":"3.5.3-dev-88-g5bf199f9",
	"experiment_name":"DryRun",
	"experiment_date":"2022-05-03T17:25:09.517900Z",
	"experiment_author":"chinmai",
	"experiment_mission":"Dryrun"}}}}

**Comment by vincentraymond-ua** [comment]
That is the export message that is generated when you export the .metadata file. I believe the data.index field represents the index that you exported, not necessarily the index containing the data. 

I believe the correct index will start with "logstash-" and then the date.

**Comment by adarshp** [comment]
See elasticsearch Python API: https://elasticsearch-py.readthedocs.io/en/v8.2.0/

You should be able to use globs when specifying indices. Fingers crossed!

**Comment by eduongAZ** [comment]
Worked with Vincent. Metadata can be extracted by going to metadata server (testbed is running) on ToM browser with address `localhost:8082`.

Look for index `logstash` after selection session.

**Comment by adarshp** [comment]
(See also #311 )

**Comment by paulosoaresua** [comment]
I was able to extract data using elastic search library in Python. I can implement this very quickly and incorporate to the Uber script, but I am afraid I don't have buffer now. If we can start the experiments in August 1st  extracting the data manually, I can automate this as soon as I get back in August 12th. It shouldn't take more than a week to deploy this. 

I can also pass this task to Eric but he's also working on the coordination model and there's a learning curve there.

**Comment by adarshp** [comment]
Ok, fair enough. That sounds good to me.
