### ISSUE TITLE
Microphone picking up other player's utterances

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#319]
ASR speech agent picks up utterance of one player from another player's microphone.

**Comment by vincentraymond-ua** [comment]
We noticed this at the lab today when testing the Testbed and ASR_Agent. The new microphones are so sensitive that they were able to pick up speaking from the control room.

**Comment by adarshp** [comment]
Update: We have one last set of headphones to test. Hopefully they don't have this issue. Let's see how it goes and revisit this issue later if necessary.

**Comment by eduongAZ** [comment]
In today's test, the microphones seemed to pick up background voices. We evaluated the messages posted in agent/asr/# and agent/asr/final and saw that a microphone grouped the voice lines of two people, one person talking after the other person finished talking.

Suggestion: use non-noise-canceling earbuds such that the participants can hear each other talking from the outside earbuds. This way, we do not need to use Mumble, which delays speech by a few milliseconds and makes the participants uncomfortable. We only use earbuds to allow the participants to watch the training video and listen to sound in Minecraft.

Suggestion: use a directional microphone to eliminate background noise.

**Comment by eduongAZ** [comment]
Problem solved in #278 with the new directional microphones.
