### ISSUE TITLE
Make the baseline tasks program more robust to reconnections and disconnections

### ISSUE THREAD

**Issue by paulosoaresua** [ml4ai/tomcat#330]

**Comment by paulosoaresua** [comment]
To check if the connection between client and server was successfully established, the experimenter has to look at the messages at the baseline tasks server. The uber script allows the experimenter to try to reconnect in case of failure. However, if the client is already connected and the experimenter tries to reconnect again the client breaks. Instead, it should ignore if already connected to the server or switch connection if the server address is different. 

Similar behavior happens in case the client gets disconnected. Once disconnected, there's no rejoin. The baseline task program has to start over.

**Comment by adarshp** [comment]
Update: This is not a bug, rather a general robustness improvement. Will put this in the category of 'general improvements'.

**Comment by eduongAZ** [comment]
This feature is already implemented in the baseline task. The server checks for duplicate in the client's name and reject the connection unless the client chooses a different name. This has also been tested in the lab: The Uberscript tried to start experimenter client and connects to the server multiple times, during which the server rejected the reconnections and warned the user to choose a different name for the client.
