### ISSUE TITLE
Program to retrieve survey data from Redcap

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#334]
We should have a program (Python?) to retrieve the Redcap survey data and output a CSV.

We may want to extend the program to publish the data to the message bus in the future so that our ASI agent can use it to form a prior model of the participants.

**Comment by adarshp** [comment]
@rchamplin is working on this using https://github.com/redcap-tools/PyCap. He is waiting on REDCap credentials.

**Comment by rchamplin** [comment]
I have developed a script "export_redcap_data" and it makes calls to "export_redcap_data.py".
