### ISSUE TITLE
Inventory script

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#362]
There are a number of files of different kinds generated for each team. We should have an inventory/QC script that checks if all the necessary files have been generated, and warns us if that is not the case. We may want to have the UberScript script invoke the inventory script at the end of each team's data collection.

**Comment by CalebUAz** [comment]
TODO: 
1. Check for audio files and vocalics exported from Minecraft.
2. Check for XDF files. 
3. Check for pupil capture files.

**Comment by CalebUAz** [comment]
Changes requested by Paulo: _"script should check if there’s a log folder in testbed_logs instead of checking for the .tar file itself."_

**Comment by adarshp** [comment]
This has been taken care of by @rchamplin .
