### ISSUE TITLE
Correct way to extract .metadata files from testbed

### ISSUE THREAD

**Issue by CalebUAz** [ml4ai/tomcat#378]
Steps followed to extract metadata files:

1. Goto localhost:8082/dashboard, made sure the testbed is running and metadata-app is online
2. Select logstash-2022.06.03.000004
3. Select the latest trail under UUID
4. Once I hit export I get the message saying '0 documents exported'

**Comment by CalebUAz** [comment]
We need the trial ID to have a better naming convention even if it's a dry run.

**Comment by CalebUAz** [comment]
@adarshp was able to extract .metadata files with `logstash-2022.07.07-000005`. 

TODO: 
Update the manual

**Comment by adarshp** [comment]
Specifically - the manual should be updated to have the experimenter select the most recent logstash index. Typing 'lo' into the 'Select Index' field will surface all the existing logstash indices as suggestions.

**Comment by adarshp** [comment]
This extraction step will be automated by August 19 with a script (see #316)

**Comment by CalebUAz** [comment]
Also you have use Chrome not Firefox to extract metadata files.
