### ISSUE TITLE
Script to validate Minecraft data

### ISSUE THREAD

**Issue by CalebUAz** [ml4ai/tomcat#385]
@eduongAZ @paulosoaresit Any thoughts on this?

**Comment by adarshp** [comment]
@CalebUAz - what do you mean by validating the Minecraft data?

**Comment by CalebUAz** [comment]
> @CalebUAz - what do you mean by validating the Minecraft data?

@adarshp Eric said he wanted to validate the Minecraft data by verifying if the difference in the first and last time stamp is same as the time taken for that particular mission.

**Comment by adarshp** [comment]
I hadn't thought of doing it, but sure, why not.

**Comment by CalebUAz** [comment]
Metadata validation would something like this:

![Image](https://user-images.githubusercontent.com/90938130/185516381-f5644a23-32a4-4456-8d8a-c05ca1aa4f1d.png)

**Comment by adarshp** [comment]
Update: @paulosoaresua will send @CalebUAz the correct message to look for for mission start/end.

**Comment by adarshp** [comment]
Closed by #405
